routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/test', 'TestController@index');
// Route::get('/fetch-categories', 'TestController@fetchCategories');

Route::get('/', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function(){

    // Route::resource('profiles', 'ProfileController');
    // Route::resource('messages', 'MessageController');
    // Route::resource('friends', 'FriendsController');

    Route::resources([
        'profiles' => 'ProfileController',
        'messages' => 'MessageController',
        'friends' => 'FriendsController',
        'categories' => 'CategoryController'
    ]);
    
    
    Route::get('/profile/edit/pass', 'ProfileController@editPassword')->name('edit-pass');
    Route::put('/profile/{user}/change-pass', 'ProfileController@updatePassword')->name('update-pass');
    
    Route::put('/user/add-game/{game}', 'ProfileController@addGame')->name('add-game');
    Route::delete('/user/remove-game/{game}', 'ProfileController@removeGame')->name('del-game');
    
    Route::get('/profile/{user}/library', 'UserLibraryController')->name('user-game-lib');

    Route::post('/buddies', 'SearchBuddyController')->name('buddy');

    
    // Route::get('/profiles', 'ProfileController@index')->name('profiles');
    // Route::get('/profiles/{user}', 'ProfileController@show')->name('profiles.show');
    // Route::get('/profiles/{user}/edit', 'ProfileController@edit')->name('profiles.edit');
    // Route::put('/profiles/{user}', 'ProfileController@update')->name('profiles.edit');
    
    // Route::get('/friends', 'FriendsController@index')->name('friend-list');
    // Route::post('/friends/{user}', 'FriendsController@store')->name('add-friend');
    // Route::delete('friends/{user}', 'FriendsController@destroy')->name('remove-friend');
});

Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function(){

    Route::get('/','HomeController')->name('index');
    Route::resource('games', 'GameController');
    Route::resource('users', 'UserController');
    Route::resource('categories', 'CategoryController');

    
    Route::post('games/image/', 'GameController@addImage')->name('add-image');
    Route::put('games/image/{image}', 'GameController@setMainImage')->name('set-main-image');
    Route::delete('games/image/{image}', 'GameController@deleteImage')->name('delete-image');
});

Route::resource('games','GameController')->only(['index','show']);

// Route::get('/games', 'GameController@index')->name('games');
// Route::get('/games/{game}', 'GameController@show')->name('games.show');

resources/views/buddies.blade.php
<x-master>
    @forelse ($users as $key => $user) 
        
        <p>user: <a href="{{ route('profiles.show',$user->username) }}"></a>{{ $user->username }}</p>
        <img width="50" src="{{ $user->avatar }}" alt="">
        <p>matching searches: 
            <ul>
                @foreach ($user->games as $game)
                    
                    @if ($matches->contains($game->name))
                        <a href="{{ route('game', $game->id) }}"><li>{{ $game->name }}</li></a>
                    @endif

                @endforeach
            </ul>
        </p>
    @empty
        <p>No users matched your search</p>
    @endforelse
</x-master>

resources/views/friends.blade.php
<x-master>
    @forelse ($user->friends as $friend)
        <div>
            <a href="{{ route('profiles.show',$friend->username) }}"><h2>{{ $friend->name }}</h2></a>

            
            <img class="rounded-full mr-2 " width="50" 
            src="{{ $friend->avatar }}" 
            alt="{{ $friend->username }}'s avatar"
            >

        </div>
    @empty
        <p>You don't have any friends yet</p>
    @endforelse
</x-master>

resources/views/home.blade.php
<x-master>

    <div class="flex justify-center mb-5">
        <a class="text-xl bg-orange-500" href="{{ route('games.index') }}">Explore All games</a>
    </div>
    <div class="grid grid-cols-3 gap-10">

        @forelse ($categories as $category)

        <div class="">
            <h2>{{ $category->name }}</h2>
            <a href="{{ route('categories.show',$category) }}">
                <img width="150" src="{{ $category->image }}" alt="{{ $category->name }}'s image'">
            </a>
        </div>

        @empty
        <p>No categories to show</p>
        @endforelse
    </div>

</x-master>

resources/views/test.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="{{ asset('js/app.js') }}"defer></script>
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>

<h1>Test</h1>


<h2>Categories</h2>
{{-- <table id="categories_table" class="display">
    <thead>
        <tr>
            <th>Category Cover</th>
            <th>Name</th>
            <th>Created On</th>
            <th>Last Updated</th>
            <th>Games</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody>

    </tbody>
</table> --}}

    
<div id="app">
    <modal-component></modal-component>
    <example-component></example-component>
</div>


</body>
</html>

resources/views/user-bar.blade.php
<div>

    <div class="my-5 mx-3">

        <div class="flex justify-end">

            <div class="">
                <a class="bg-red-500 mt-4 rounded-lg shadow py-2 px-2 text-white" href="{{ route('logout') }}" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="">
                    @csrf
                </form>
            </div>

        </div>


        <div>
            <div>
                <a href="{{ route('friends.index') }}">Friends: {{ currentUser()->friends->count()}} </a>
            </div>
        </div>


        <div class="flex">

            <a class="text-xl" href="{{ route('profiles.show',auth()->user()) }}">
                Welcome, {{ Auth::user()->name }}!
            </a>
            <div>
                <img src="{{ currentUser()->avatar }}" alt="" class="rounded-full mr-2 " width="50">
            </div>
        </div>

    </div>

</div>