routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/test', 'TestController@index');
// Route::get('/fetch-categories', 'TestController@fetchCategories');

Route::get('/', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function(){

    // Route::resource('profiles', 'ProfileController');
    // Route::resource('messages', 'MessageController');
    // Route::resource('friends', 'FriendsController');

    Route::resources([
        'profiles' => 'ProfileController',
        'messages' => 'MessageController',
        'friends' => 'FriendsController',
        'categories' => 'CategoryController'
    ]);
    
    
    Route::get('/profile/edit/pass', 'ProfileController@editPassword')->name('edit-pass');
    Route::put('/profile/{user}/change-pass', 'ProfileController@updatePassword')->name('update-pass');
    
    Route::put('/user/add-game/{game}', 'ProfileController@addGame')->name('add-game');
    Route::delete('/user/remove-game/{game}', 'ProfileController@removeGame')->name('del-game');
    
    Route::get('/profile/{user}/library', 'UserLibraryController')->name('user-game-lib');

    Route::post('/buddies', 'SearchBuddyController')->name('buddy');

    
    // Route::get('/profiles', 'ProfileController@index')->name('profiles');
    // Route::get('/profiles/{user}', 'ProfileController@show')->name('profiles.show');
    // Route::get('/profiles/{user}/edit', 'ProfileController@edit')->name('profiles.edit');
    // Route::put('/profiles/{user}', 'ProfileController@update')->name('profiles.edit');
    
    // Route::get('/friends', 'FriendsController@index')->name('friend-list');
    // Route::post('/friends/{user}', 'FriendsController@store')->name('add-friend');
    // Route::delete('friends/{user}', 'FriendsController@destroy')->name('remove-friend');
});

Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function(){

    Route::get('/','HomeController')->name('index');
    Route::resource('games', 'GameController');
    Route::resource('users', 'UserController');
    Route::resource('categories', 'CategoryController');

    
    Route::post('games/image/', 'GameController@addImage')->name('add-image');
    Route::put('games/image/{image}', 'GameController@setMainImage')->name('set-main-image');
    Route::delete('games/image/{image}', 'GameController@deleteImage')->name('delete-image');
});

Route::resource('games','GameController')->only(['index','show']);

// Route::get('/games', 'GameController@index')->name('games');
// Route::get('/games/{game}', 'GameController@show')->name('games.show');

resources/views/admin/_categories_panel.blade.php
<h1>Categories</h1>


    <div>
        <table id="categories_table" class="display">
            <thead>
                <tr>
                    <th>Category Cover</th>
                    <th>Name</th>
                    <th>Created On</th>
                    <th>Last Updated</th>
                    <th>Games</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categories as $category)
                <tr>
                    <td class="d-flex justify-content-center">
                        <img width="50" src="{{ $category->image }}" alt="">
                    </td>
                    <td>{{ $category->name }}</td>
                    @if ($category->created_at && $category->updated_at)
                        <td>{{ $category->created_at->diffForHumans() }}</td>
                        <td>{{ $category->updated_at->diffForHumans() }}</td>
                    @else
                        <td>{{ $category->created_at }}</td>
                        <td>{{ $category->updated_at }}</td>
                    @endif
                    <td><a href="{{ route('categories.show', $category) }}">
                        {{ $category->games()->count() }}
                        </a>
                    </td>
                    <td>
                        
                        

                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#category-{{$category->id}}-modal">
                                Edit
                            </button>
                                            
                                            <!-- Modal -->
                            <div class="modal fade" id="category-{{$category->id}}-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Edit category data</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>
                                    <div class="modal-body">
                                        <form enctype="multipart/form-data" id="category-{{ $category->id}}" method="POST" action="{{ route('admin.categories.update', $category) }}">
                                            @csrf
                                            @method('put')
                                            <label for="name">Change category name</label>
                                            <input type="text" name="name" value="{{ $category->name }}" class="border border-primary rounded" >
                                            <br>
                                            <label for="image">Change category image</label>
                                            <input type="file" name="image" >
                                        
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                    <button type="submit" form="category-{{$category->id}}" class="btn btn-primary">Edit Category</button>
                                    </div>
                                </div>
                                </div>
                            </div>

                    

                    </td>
                    <td>
                        <form  method="POST" action="{{ route('admin.categories.destroy',$category) }}">
                            @csrf
                            @method('delete')
                            <button type="submit">DELETE</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createCategoryModal">
        Create New Category
    </button>
    
    <!-- Modal CREATE CATEGORY -->
    <div class="modal fade" id="createCategoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Enter data</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <form enctype="multipart/form-data" id="category_form" method="POST" action="{{ route('admin.categories.store') }}">
                    @csrf
                    <label for="n">Enter category name</label>
                    <input type="text" name="name" id="n" class="border border-primary" >
                    <br>
                    <label for="i">Upload an image</label>
                    <input type="file" name="image" id="i" >
                   
                </form>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" form="category_form" class="btn btn-primary">Make Category</button>
            </div>
        </div>
        </div>
    </div>

resources/views/admin/_games_panel.blade.php
<h1>Games</h1>

    <div>
        <table id="games_table" class="display">
            <thead>
                <tr>
                    <th>Main Cover</th>
                    <th>Name</th>
                    <th>Added on</th>
                    <th>Last Updated</th>
                    <th>Category</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($games as $game)
                <tr>
                    <td>
                        <x-display-image :game=$game></x-display-image>
                    </td>
                    <td>{{ $game->name }}</td>
                    @if ($game->created_at && $game->updated_at)
                        <td>{{ $game->created_at->diffForHumans() }}</td>
                        <td>{{ $game->updated_at->diffForHumans() }}</td>
                    @else
                        <td>{{ $game->created_at }}</td>
                        <td>{{ $game->updated_at }}</td>
                    @endif
                <td><a href="{{ route('categories.show', $game->category) }}">{{ $game->category->name }}</a></td>
                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#game-{{$game->id}}-modal">
                            Edit
                        </button>
                                        
                        <!-- Modal EDIT GAME-->
                        <div class="modal fade" id="game-{{$game->id}}-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Edit game data</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                                <div class="modal-body">
                                    <form enctype="multipart/form-data" id="game-{{ $game->id }}" method="POST" action="{{ route('admin.games.update', $game) }}">
                                        @csrf
                                        @method('put')

                                        <label for="name">Change game name</label>
                                        <input type="text" name="name" value="{{ $game->name }}" class="border border-primary rounded" >
                                        <br>

                                        <label for="categories">Change category:</label>
                                        <select class="border border-primary rounded" name="categories" id="categories">
                                            @foreach ($categories as $category)
                                                <option value="{{ $category->id }}">{{ $category->name }}</option>

                                                @if ($game->category_id == $category->id)
                                                <option value="{{ $category->id }}" selected="selected" hidden >{{ $category->name }}</option>
                                                @endif
                                                
                                            @endforeach
                                        </select>

                                        <br>
                                        
                                        <label class="align-top" for="description">Change game description</label>
                                        <textarea class="border border-primary rounded" 
                                                name="description" 
                                                id="" cols="30" rows="4" 
                                                value>{{ $game->description }}
                                        </textarea>
                                        <br>
                                        
                                    </form>

                                    <div class="">
                                       
                                        <form action="{{ route('admin.add-image') }}" method="POST" enctype="multipart/form-data">
                                            @csrf
                                            <label for="image">Add image</label>
                                            <input type="hidden" name="gameId" value="{{ $game->id }}">
                                            <input type="file" name="image" >
                                            <input type="submit" value="Upload">
                                        <br>
                                        </form>
                                        @forelse ($game->images as $image)

                                            <img class="img-thumbnail" style="width:200px;height:200px;overflow:hidden" src="{{$image->path }}" alt="">
                                            @if ($image->isMain != NULL)
                                                <p>Main image</p>
                                            @endif

                                            
                                            <form action="{{ route('admin.set-main-image', $image) }}" method="post">
                                                @csrf
                                                @method('put')

                                                @if ($image->isMain == null)
                                                    <input type="submit" name="changeImageBtn" value="Make Main Image">
                                                @endif

                                            </form>
                                            <form action="{{ route('admin.delete-image', $image) }}" method="post">
                                                @csrf
                                                @method('delete')
                                                
                                                <input type="submit" name="removeImageBtn" value="Remove Image">
                                            </form>
                                        @empty
                                            <p>No images uploaded yet</p>
                                        @endforelse
                                    </div>
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <button type="submit" form="game-{{ $game->id }}" class="btn btn-primary">Edit Game</button>
                                </div>
                            </div>
                            </div>
                        </div>
                    </td>
                    <td>
                        <form method="POST" action="{{ route('admin.games.destroy', $game) }}">
                            @csrf
                            @method('delete')

                            <button type="submit">
                                DELETE
                            </button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>


    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addGameModal">
        Add New Game
    </button>
    
    <!-- Modal Add game-->
    <div class="modal fade" id="addGameModal" tabindex="-1" role="dialog" aria-labelledby="gameLabelModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="gameLabelModal">Enter game data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    <form enctype="multipart/form-data" id="add_game_form" method="POST" action="{{ route('admin.games.store') }}">
                        @csrf
                        <label for="n">Game name</label>
                        <input type="text" name="name" id="n" class="border border-primary" >
                        <br>
                        <label class="align-top">Description</label>
                        <textarea class="border border-primary rounded" 
                            name="description" 
                            id="" cols="30" rows="4" 
                            value
                            ></textarea>
                            
                        <br>
                        <br>
                        <label>Choose category</label>
                        <select class="border border-primary rounded" name="categories">
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                        <br>
                        <label for="i">Main image/cover</label>
                        <input type="file" name="image" id="i" > 
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" form="add_game_form" class="btn btn-primary">Add game</button>
                </div>
            </div>
        </div>
    </div>
   
    <input type="hidden" id="gameId" value="{{ Session::get('editModal','index') }}"></input>

resources/views/admin/_users_panel.blade.php
<h1>Users</h1>
<div>
    <table id="users_table" class="display">
        <thead>
            <tr>
                <th>Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Registered On</th>
                <th>Last Updated</th>
                <th>Games playing</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
            <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->username }}</td>
                <td>{{ $user->email }}</td>
                @if ($user->created_at && $user->updated_at)
                        <td>{{ $user->created_at->diffForHumans() }}</td>
                        <td>{{ $user->updated_at->diffForHumans() }}</td>
                    @else
                        <td>{{ $user->created_at }}</td>
                        <td>{{ $user->updated_at }}</td>
                    @endif
                <td class="text-center"><a href="{{ route('user-game-lib', $user->username) }}">{{ $user->games()->count()}}<a></td>
                <td>
                    <a href="{{ route('profiles.show', $user) }}">VIEW</a>
                </td>
                <td>
                    <form method="POST" action="{{ route('admin.users.destroy', $user->id) }}">
                        @csrf
                        @method('DELETE')
                        <button type="submit">DELETE</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>


    

resources/views/admin/index.blade.php
<x-admin-page>

    @push('bootstrap')
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @endpush
    
    @if(session('message'))
    <h1 class="text-success">{{session('message')}}</h1>
    @endif
    <h1>Admin Panel</h1>


    
    @include('admin._users_panel')


    @include('admin._categories_panel')


    @include('admin._games_panel')

</x-admin-page>

<script>


    $(document).ready( function () {
        $('#games_table').DataTable();
        $('#categories_table').DataTable();
        $('#users_table').DataTable();

        if ($("#gameId").val() != 'index') {
            let gameId = "#game-"+$("#gameId").val()+"-modal";
            console.log(gameId);
            $(gameId).modal('show')
        }
    } );
</script>